<?php

use App\Enums\CategoryType;
use App\Enums\TransactionType;
use App\Models\Account;
use App\Models\Category;
use App\Models\Invoice;
use App\Models\RecurringTransaction;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Support\Carbon;

test('generates occurrences from the start date up to the current month', function () {
    $this->travelTo(Carbon::parse('2026-09-15'));

    $user = User::factory()->create();
    $account = Account::factory()->for($user)->create();
    $category = Category::factory()->for($user)->create(['type' => CategoryType::Expense]);

    $recurring = RecurringTransaction::factory()->create([
        'user_id' => $user->id,
        'account_id' => $account->id,
        'category_id' => $category->id,
        'type' => TransactionType::Expense,
        'amount' => 100,
        'start_date' => '2026-06-05',
    ]);

    $recurring->generateDueOccurrences();

    $dates = $recurring->transactions()->orderBy('date')->pluck('date')->map->toDateString();

    expect($dates->all())->toBe(['2026-06-05', '2026-07-05', '2026-08-05', '2026-09-05']);
});

test('does not create duplicate occurrences when called again', function () {
    $this->travelTo(Carbon::parse('2026-09-15'));

    $user = User::factory()->create();
    $recurring = RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-08-05']);

    $recurring->generateDueOccurrences();
    $recurring->generateDueOccurrences();

    expect($recurring->transactions()->count())->toBe(2);
});

test('inactive recurring transactions are not generated by generateDueForUser', function () {
    $this->travelTo(Carbon::parse('2026-09-15'));

    $user = User::factory()->create();
    RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-08-05', 'is_active' => false]);

    RecurringTransaction::generateDueForUser($user);

    expect(Transaction::count())->toBe(0);
});

test('clamps the day to the shortest month when generating occurrences', function () {
    $this->travelTo(Carbon::parse('2026-04-01'));

    $user = User::factory()->create();
    $recurring = RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-01-31']);

    $recurring->generateDueOccurrences();

    $dates = $recurring->transactions()->orderBy('date')->pluck('date')->map->toDateString();

    expect($dates->all())->toBe(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30']);
});

test('credit card expense occurrences are linked to the invoice of their month', function () {
    $this->travelTo(Carbon::parse('2026-09-01'));

    $user = User::factory()->create();
    $card = Account::factory()->for($user)->creditCard()->create(['closing_day' => 10, 'due_day' => 17]);
    $category = Category::factory()->for($user)->create(['type' => CategoryType::Expense]);

    $recurring = RecurringTransaction::factory()->create([
        'user_id' => $user->id,
        'account_id' => $card->id,
        'category_id' => $category->id,
        'type' => TransactionType::Expense,
        'start_date' => '2026-07-05',
    ]);

    $recurring->generateDueOccurrences();

    $referenceMonths = $recurring->transactions()->with('invoice')->get()
        ->map(fn ($transaction) => $transaction->invoice->reference_month)
        ->all();

    expect($referenceMonths)->toBe([7, 8, 9])
        ->and(Invoice::where('account_id', $card->id)->count())->toBe(3);
});

test('generateDueForUser only generates for the given user\'s recurring transactions', function () {
    $this->travelTo(Carbon::parse('2026-09-15'));

    $user = User::factory()->create();
    $otherUser = User::factory()->create();

    RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-09-01']);
    RecurringTransaction::factory()->create(['user_id' => $otherUser->id, 'start_date' => '2026-09-01']);

    RecurringTransaction::generateDueForUser($user);

    expect(Transaction::where('user_id', $user->id)->count())->toBe(1)
        ->and(Transaction::where('user_id', $otherUser->id)->count())->toBe(0);
});

test('generateAllDue generates active recurring transactions across every user', function () {
    $this->travelTo(Carbon::parse('2026-09-15'));

    $user = User::factory()->create();
    $otherUser = User::factory()->create();

    RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-09-01', 'is_active' => true]);
    RecurringTransaction::factory()->create(['user_id' => $otherUser->id, 'start_date' => '2026-09-01', 'is_active' => true]);
    RecurringTransaction::factory()->create(['user_id' => $user->id, 'start_date' => '2026-09-01', 'is_active' => false]);

    RecurringTransaction::generateAllDue();

    expect(Transaction::count())->toBe(2);
});
